// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as StateRoute } from './routes/state'
import { Route as TransactionsRoute } from './routes/transactions'
import { Route as NetworkRoute } from './routes/network'
import { Route as BlocksRoute } from './routes/blocks'
import { Route as IndexRoute } from './routes/index'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/blocks': {
      preLoaderRoute: typeof BlocksRoute
      parentRoute: typeof rootRoute
    }
    '/network': {
      preLoaderRoute: typeof NetworkRoute
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      preLoaderRoute: typeof TransactionsRoute
      parentRoute: typeof rootRoute
    }
    '/state': {
      preLoaderRoute: typeof StateRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BlocksRoute,
  NetworkRoute,
  TransactionsRoute,
  StateRoute,
])
